[project]
name = "mice"
version = "0.2.0"
description = "Train and evaluate MICE models for efficient IR"
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = [
    "datamaestro>=1.5.2",
    "experimaestro-ir[anserini,neural]",
    "ir-datasets",
    "pandas>=2.3.1",
    "tensorboard>=2.20.0",
    "pyserini>=0.21.0",
    "faiss-cpu",
    "sentence-transformers",
    "datasets",
    "accelerate>=1.11.0",
    "lightning",
    "torch<2.8.0",
    "matplotlib>=3.10.8",
    "pylate>=1.3.4",
]

[tool.uv]
package = true

override-dependencies = [
    "nmslib ; sys_platform == 'never'",
]

[tool.uv.sources]
experimaestro = { path = "experimaestro-python", editable = true }
experimaestro-ir = { path = "experimaestro-ir", editable = true }
ir-datasets = { git = "https://github.com/bpiwowar/ir_datasets.git" }

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "notebook",
]
